### ISSUE TITLE
Styling fixes for LandPKS website secondary navigation

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/landpotential-wp-theme#90]
There are a couple of things I can't figure out how to do:

- Make the collapsed menu at the full width of the container (25% of the screen) like it is when open with longer named submenu items. I'd like it to be the full width all the time. 
- A small indent for submenu items, including level 2 and 3. 
- Keep the navigation section accordion open as you open new pages in that section.
- Pin the footer to bottom of viewport. 

![Image](https://github.com/techmatters/terraso-web-client/assets/8915145/0ec07707-4dea-4675-a3a0-21e8a3f4d06c)

![Image](https://github.com/techmatters/terraso-web-client/assets/8915145/4655fe10-21dd-40c7-aaaf-a03bf0ad7522)

**Comment by paulschreiber** [comment]
Fixed with 4cddf5974695a002c715f212c7945ff6f236790a.
